name: text_to_speech_api
description: A simple wrapper for accessing Google's Text-To-Spech API and converting the results to MP3 files.
version: 0.1.0
author: Luca Demmel <luca.demmel@incudy.de>
homepage: https://www.lucademmel.com

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  path_provider: ^0.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
